### ISSUE TITLE
リポジトリ名がstudy_makingになっている

### ISSUE THREAD

**Issue by ghost** [kwakahara/study_making_201511#3]
タイポです。

**Comment by kwakahara** [comment]
指摘事項が全てcloseされた後にマージ済みの物を別名リポジトリとして提出します。

**Comment by ghost** [comment]
それだとこれから実施する改善変更の履歴が残らないのでむしろこっちを先にやるべきでは、と思ったのですが
後で実施すると判断した理由を教えて下さい。

**Comment by YuichiKimura** [comment]
試してみましたがリポジトリ名変更してもissues消えませんでした。

**Comment by ghost** [comment]
issuesもそうですがブランチとコミットログはどうでしょう？

**Comment by YuichiKimura** [comment]
ブランチもコミットログもそのままでした。

**Comment by ghost** [comment]
じゃあそのまま移管できれば本チケットはクローズということですかね。

**Comment by YuichiKimura** [comment]
そうですね。

**Comment by ghost** [comment]
Options⇒Settingsからできるのか。  
@kwakahara さんは「別名リポジトリとして提出」と言っているので
cloneして別名にpushし直すと思っていたのだが、それは必要なさそうだよね。

**Comment by kwakahara** [comment]
修正しました

**Comment by ghost** [comment]
はい、ありがとうございます。
今後もすぐ出来ることはすぐやりましょう。

**Comment by YuichiKimura** [comment]
> ryoichi-obaraさん
> クローズお願いします。
