### ISSUE TITLE
日付表示

### ISSUE THREAD

**Issue by YuichiKimura** [kwakahara/study_making_201511#6]
2月が31日まで出ます。
他の月も存在しない日が出てしまいます。 @d44df80

**Comment by YuichiKimura** [comment]
2016年4月で試してみたら最終週が2行出てしまいました。
確認をお願いします。＠b2b4326

**Comment by kwakahara** [comment]
不具合の修正を行いましたが、issue8の実装で修正対応ができておりますので、そちらで評価をお願いします。
https://github.com/kwakahara/study_marking_201511/blob/branch_201511_%2308/js/study-marking-calendar.js

**Comment by YuichiKimura** [comment]
issue8がmasterにマージされたらこちらもクローズとします。

**Comment by YuichiKimura** [comment]
確認しました。クローズします。
