### ISSUE TITLE
コーディングについて

### ISSUE THREAD

**Issue by YuichiKimura** [kwakahara/study_making_201511#8]
月初の曜日ごとに書いていますがまとめた書き方はできないでしょうか。 @d44df80

**Comment by kwakahara** [comment]
まとめた書き方について、現在対応中なのですが、まだ解決策が見つかっておらず、実装が完了していません。
もう少し日数をいただけないでしょうか。

**Comment by kwakahara** [comment]
ほぼ作り直しを行いましたので、実装が変わっている個所がございます。

**Comment by YuichiKimura** [comment]
確認しました。すっきりしていて良いと思います。
masterへマージしてください。

**Comment by YuichiKimura** [comment]
確認しました。クローズします。
